#!/usr/bin/env python3
"""Generate the per-topic skill bundles under plugins/ from skills/.

skills/<name>/ stays the one place a skill is edited. Each bundle is a plugin
folder holding copies of its skills, so a harness can install the default
pair without the review and design skills:

  agy plugin install https://github.com/yschimke/skills/tree/main/plugins/compose-skills
  /plugin install compose-skills@yschimke-skills

The root plugin (yschimke-skills, every skill) is unchanged.

Usage:
  python3 scripts/generate-bundles.py           # rewrite plugins/ and the marketplace
  python3 scripts/generate-bundles.py --check   # exit 1 if they are out of date
"""

import json
import re
import shutil
import sys
import tempfile
from pathlib import Path
from typing import NoReturn

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
PLUGINS = ROOT / "plugins"
MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
INSTALL_SH = ROOT / "scripts" / "install.sh"
ANTIGRAVITY_SCHEMA = "https://antigravity.google/schemas/v1/plugin.json"

# Every skill belongs to exactly one bundle. The first is the default and must
# match install.sh: compose-preview plus DEFAULT_COMPANION_SKILLS.
BUNDLES = {
    "compose-skills": {
        "description": "Render Compose @Preview functions and author designs over MCP (the default skills).",
        "skills": ["compose-preview", "compose-ui-builder"],
    },
    "compose-review-skills": {
        "description": "Review Compose UI pull requests, set up preview CI, and check design parity.",
        "skills": ["compose-preview-review", "compose-preview-ci", "design-parity-review"],
    },
    "compose-design-skills": {
        "description": "Export Compose renders to design tools: design boards, sticker-sheet catalogs, and Figma import.",
        "skills": ["compose-preview-design-board", "compose-design-catalog", "figma-catalog-import"],
    },
}
DEFAULT_BUNDLE = "compose-skills"
# Test runs leave __pycache__ next to bundled scripts; never ship it.
IGNORED = shutil.ignore_patterns(".DS_Store", "__pycache__", "*.pyc")


def fail(message: str) -> NoReturn:
    print(f"generate-bundles: {message}", file=sys.stderr)
    sys.exit(1)


def check_assignment() -> None:
    on_disk = sorted(p.name for p in SKILLS.iterdir() if (p / "SKILL.md").is_file())
    assigned = [name for bundle in BUNDLES.values() for name in bundle["skills"]]
    duplicates = sorted({name for name in assigned if assigned.count(name) > 1})
    if duplicates:
        fail(f"in more than one bundle: {', '.join(duplicates)}")
    if sorted(assigned) != on_disk:
        missing = sorted(set(on_disk) - set(assigned))
        unknown = sorted(set(assigned) - set(on_disk))
        fail(f"BUNDLES and skills/ disagree; add to a bundle: {missing or '-'}; not in skills/: {unknown or '-'}")
    match = re.search(r"^DEFAULT_COMPANION_SKILLS=\(\n(.*?)^\)", INSTALL_SH.read_text(), re.M | re.S)
    if not match:
        fail("DEFAULT_COMPANION_SKILLS not found in scripts/install.sh")
    defaults = ["compose-preview"] + match.group(1).split()
    if sorted(defaults) != sorted(BUNDLES[DEFAULT_BUNDLE]["skills"]):
        fail(f"{DEFAULT_BUNDLE} must match install.sh's default skills: {defaults}")


def dump(value: dict) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def write_bundle(target: Path, name: str, bundle: dict) -> None:
    target.mkdir(parents=True)
    for skill in bundle["skills"]:
        shutil.copytree(SKILLS / skill, target / "skills" / skill, ignore=IGNORED)
    (target / "plugin.json").write_text(dump(
        {"$schema": ANTIGRAVITY_SCHEMA, "description": bundle["description"], "name": name}))
    # Same version as the root plugin; release-please bumps all of them together.
    version = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())["version"]
    (target / ".claude-plugin").mkdir()
    (target / ".claude-plugin" / "plugin.json").write_text(dump({
        "name": name,
        "description": bundle["description"],
        "version": version,
        "author": {"name": "Yuri Schimke", "url": "https://github.com/yschimke"},
        "repository": "https://github.com/yschimke/skills",
        "license": "Apache-2.0",
    }))
    listing = "\n".join(f"- [`{s}`](../../skills/{s}/SKILL.md)" for s in bundle["skills"])
    (target / "README.md").write_text(
        f"# {name}\n\n{bundle['description']}\n\n{listing}\n\n"
        "Generated by `scripts/generate-bundles.py` from `skills/`; edit the skills there.\n")


def marketplace_text() -> str:
    marketplace = json.loads(MARKETPLACE.read_text())
    entries = [p for p in marketplace["plugins"] if p["name"] not in BUNDLES]
    entries += [{"name": name, "source": f"./plugins/{name}", "description": bundle["description"]}
                for name, bundle in BUNDLES.items()]
    marketplace["plugins"] = entries
    return dump(marketplace)


def generate(out: Path) -> None:
    for name, bundle in BUNDLES.items():
        write_bundle(out / name, name, bundle)


def tree(root: Path) -> dict[str, bytes]:
    return {str(p.relative_to(root)): p.read_bytes() for p in root.rglob("*") if p.is_file()}


def differs(fresh: Path, current: Path) -> list[str]:
    # Byte-for-byte: filecmp.dircmp trusts matching stat signatures and
    # silently skips names such as __pycache__.
    want, have = tree(fresh), tree(current)
    return [f"plugins/{name}" for name in sorted(want.keys() | have.keys()) if want.get(name) != have.get(name)]


def main(argv: list[str]) -> None:
    check = argv[1:] == ["--check"]
    if argv[1:] not in ([], ["--check"]):
        fail("usage: generate-bundles.py [--check]")
    check_assignment()
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / "plugins"
        generate(fresh)
        if check:
            stale = differs(fresh, PLUGINS) if PLUGINS.is_dir() else ["plugins/ (missing)"]
            if MARKETPLACE.read_text() != marketplace_text():
                stale.append(".claude-plugin/marketplace.json")
            if stale:
                fail("out of date (run python3 scripts/generate-bundles.py): " + ", ".join(stale[:5]))
            print("generate-bundles: up to date")
            return
        if PLUGINS.exists():
            shutil.rmtree(PLUGINS)
        shutil.copytree(fresh, PLUGINS)
        MARKETPLACE.write_text(marketplace_text())
    print(f"generate-bundles: wrote {', '.join(BUNDLES)}")


if __name__ == "__main__":
    main(sys.argv)
